MortalKombat/MortalKombat1/Models/ErrorViewModel.cs
namespace MortalKombat1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MortalKombat/MortalKombat1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MortalKombat1.Models;
using System.Diagnostics;

namespace MortalKombat1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sobre()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MortalKombat/MortalKombat1/Controllers/LutadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Services;
using Data.Model;
using Data.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace MortalKombat1.Controllers
{
    public class LutadoresController : Controller
    {
        private readonly ILutadorRepository _repository;
        private readonly ILutadorServices _services;

        public LutadoresController(ILutadorRepository repository, ILutadorServices services)
        {
            _repository = repository;
            _services = services;
        }
        
        public IActionResult Selecao()
        {
            List<LutadorModel> listaLutadores = _repository.ObterListaPorId();
            return View(listaLutadores);
        }

        public IActionResult DueloFinal(List<int> lutadoresSelecionados)
        {
            List<LutadorModel> listaLutadoresOrdenada = _repository.ObterListaPorIdade(lutadoresSelecionados);
            listaLutadoresOrdenada = _services.RealizarCombates(listaLutadoresOrdenada);
            listaLutadoresOrdenada = _services.ObterResultadoDueloFinal(listaLutadoresOrdenada);
            return View(listaLutadoresOrdenada);
        }
        public IActionResult FinishHim(List<int> finalistasSelecionados)
        {
            List<LutadorModel> listaOrdenada = _repository.ObterListaPorIdade(finalistasSelecionados);
            return View(listaOrdenada);
        }
        public IActionResult Vencedor(List<int> finalistasSelecionados)
        {
            List<LutadorModel> listaOrdenada = _repository.ObterListaPorIdade(finalistasSelecionados);
            return View(listaOrdenada);
        }
    }
}

MortalKombat/MortalKombat1/Views/Home/Index.cshtml
@{
    Layout = null;
}
<head>
    <title>Mortal Kombat!</title>
    <link type="text/css" rel="stylesheet" href="~/css/home.css">
</head>
<body class="background">
    <a class="button-iniciar" asp-area="" asp-controller="Lutadores" asp-action="Selecao">INICIAR</a>
    <a class="button-sobre" asp-area="" asp-controller="Home" asp-action="Sobre">SOBRE</a>    
</body>
<footer>
    <div class="descritivo">
        (para uma melhor experiência ative o modo fullscreen e o audio de seu navegador)
    </div>  

</footer>

MortalKombat/MortalKombat1/Views/Home/Sobre.cshtml
@{
    Layout = null;
}
<head>
    <title>Mortal Kombat!</title>
    <link type="text/css" rel="stylesheet" href="~/css/sobre.css">
    <a class="button-retornar" asp-area="" asp-controller="HOME" asp-action="Index">RETORNAR</a>
</head>
<body class="background">
    <div class="titulo"> 
    <h1>Sobre o projeto</h1>
    </div>
    <br>
    <div class="regras">
        <a>Regras: O torneio possui regras pré-definidas, sendo estas 16 lutadores com seus atributos também pré-definidos
            (Idade, Artes Marciais, Total de Lutas, Vitórias e Derrotas). O critério de vitória é definido pela porcentagem
            de vitórias. Os lutadores se enfrentam em um sistema de chaves de oitavas e quartas de final,
            seguido pela semifinal. A ordem dos confrontos é definida pela idade, ou seja, o mais jovem enfrenta o
            segundo mais jovem, o terceiro enfrenta o quarto mais jovem, e assim por diante.</a>
    </div>
    <br />
    <div class="ideia">
        <a>
            Idéia: Aproveitando o lançamento de Mortal Kombat 1, resolvi criar minha própria versão do torneio de Mortal Kombat.
            Também me inspirei um pouco na estética neon, que pessoalmente me agrada.
        </a>
    </div>
    <div class="criacao">
        <a>
            Criação: O projeto foi criado utilizando ASP.NET, separado em camadas e utilizando o .NET 7. Foram utilizadas algumas bibliotecas,
            como o EntityFramework, e a ferramenta SQL para acesso e modificação do banco de dados.
        </a>
    </div>

</body>
<footer>
    <div class="desenvolvido">
        <a>
           Lucas Marques - 2023
        </a>
    </div>
</footer>

MortalKombat/MortalKombat1/Views/Lutadores/DueloFinal.cshtml
@model List<Data.Model.LutadorModel>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link href="~/css/duelofinal.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duelo Final!</title>
</head>
<body>
    <div class="video-player">
        <div class="descritivo">
            <a>  Ao final do torneio restaram apenas @(Model[0].Nome) e @(Model[1].Nome). Em seu ultimo suspiro, @(Model[0].Nome) surpreendeu @(Model[1].Nome) com um golpe decisivo!</a>
        </div>
        <video src="~/video/@(Model[0].Id)finish@(Model[1].Id).mp4" class="video" poster="x"></video>
        <div class="player-controls">
            <form asp-controller="Lutadores" asp-action="finishhim" method="post">
                @foreach (var item in Model)
                {
                    <input type="hidden" name="finalistasSelecionados" value="@item.Id">
                }
                <button type="submit" class="button-finish" id="finish-button">Ver Golpe</button>
            </form>
        </div>
    </div>
<script src="~/js/duelofinal.js"></script>
</body>
</html>

MortalKombat/MortalKombat1/Views/Lutadores/FinishHim.cshtml
@model List<Data.Model.LutadorModel>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link href="~/css/finishhim.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duelo Final!</title>
</head>
<body>
    <div class="video-player">
        <div class="descritivo">
            <a> @(Model[1].Nome) perdeu sua consciência. @(Model[0].Nome) encontrou uma brecha para finaliza-lo(a)!</a>
        </div>
        <video src="~/video/@(Model[0].Id)Fatality@(Model[1].Id).mp4" class="video" poster="x"></video>
        <div class="player-controls">
            <form asp-controller="Lutadores" asp-action="vencedor" method="post">
                @foreach (var item in Model)
                {
                    <input type="hidden" name="finalistasSelecionados" value="@item.Id">
                }
                <button type="submit" class="button-finish" id="finish-button">Fatality</button>
            </form>
        </div>
    </div>
    <script src="~/js/finishhim.js"></script>
</body>
</html>

MortalKombat/MortalKombat1/Views/Lutadores/Selecao.cshtml
@model IEnumerable<Data.Model.LutadorModel>

@{
    Layout = null;
}
<head>
    <link type="text/css" rel="stylesheet" href="~/css/selecao.css" />

</head>

<body>
    <div class="wrapper">
        <a class="button-menu" asp-area="" asp-controller="Home" asp-action="Index">MENU</a>
        <form asp-controller="Lutadores" asp-action="duelofinal" method="post">
            <button type="submit" class="button-iniciar" id="iniciar-button" disabled>
                <img src="~/img/Botoes/fight2.png" width="200px" height="60px" alt="Texto Alternativo da Imagem">
            </button>
            <div class="title">
                <h1>SELECIONE OS 16 LUTADORES!</h1>
            </div>

            <div class="container">
                @foreach (var item in Model)
                {
                    <label class="option_item">
                        <input type="checkbox" class="checkbox" name="lutadoresSelecionados" value="@item.Id">
                        <audio id="checkboxSound">
                            <source src="~/audio/@(item.Id).mp3" type="audio/mpeg">
                        </audio>

                        <div class="images">
                            <div class="image">
                                <img src="~/img/personagens/@(item.Id)shadow2.png" width="310px" height="320px">
                            </div>
                            <div class="image2">
                                <img src="~/img/personagens/@(item.Id).png" width="320px" height="340px">
                            </div>
                        </div>
                        <div class="option_inner">
                            <div class="tickmark">
                            </div>
                            <div class="detalhes">
                                <div class="nome">@Html.DisplayFor(modelItem => item.Nome)</div>
                                <div class="outrasInfos">
                                    <div class="Idade">Idade: @Html.DisplayFor(modelItem => item.Idade)</div>
                                    <div class="ArtesMarciais">Artes Marciais: @Html.DisplayFor(modelItem => item.ArtesMarciais)</div>
                                    <div class="TotalDeLutas">Total De Lutas: @Html.DisplayFor(modelItem => item.TotalDeLutas)</div>
                                    <div class="Derrotas">Derrotas: @Html.DisplayFor(modelItem => item.Derrotas)</div>
                                    <div class="Vitorias">Vitorias: @Html.DisplayFor(modelItem => item.Vitorias)</div>
                                </div>
                            </div>
                        </div>
                    </label>
                }
            </div>

        </form>
    </div>

</body>

<script src="~/js/selecao.js"></script>

MortalKombat/MortalKombat1/Views/Lutadores/Vencedor.cshtml
@model List<Data.Model.LutadorModel>
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <link href="~/css/vencedor.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Duelo Final!</title>
</head>
<body style="background-image: url('../img/backgrounds/@(Model[0].Id).jpg');">
        <div class= "primeiro">
        <h1>Venceu!</h1>
        </div>
        <div class="descritivo">
            <a>Total de Lutas: @(Model[0].TotalDeLutas)</a>
            <br />
            <a>Vitórias: @(Model[0].Vitorias)</a>
        </div>
    <div class="imagem-segundo" id="move-segundo">
        <img src="~/img/personagens/2.png" />
        </div>
        <div class="segundo"> 
            <h1>Segundo colocado:</h1>
       
        <h3>@(Model[1].Nome)</h3>
        <a>Total de Lutas: @(Model[1].TotalDeLutas)</a>
        <br />
        <a>Vitórias: @(Model[1].Vitorias)</a>
        </div>
    <a class="button-novamente" asp-area="" asp-controller="Lutadores" asp-action="Selecao">Jogar novamente</a>
</body>
</html>

MortalKombat/MortalKombat1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MortalKombat1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MortalKombat1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MortalKombat1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lutadores" asp-action="Index">Seleção</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MortalKombat1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>